### ISSUE TITLE
iis-root default_documents deleted every chef run

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#306]
### Cookbook version
4.1.9

### Platform Details
windows 2012

`default_documents` is not idempotent, it deletes all default documents every other chef run

After 1 chef run, the default documents is empty. 
After the second chef run, foo.aspx is added back to the default documents. 
After the 3rd chef run, the default documents is empty again

```
  iis_root 'mySite' do
    default_documents ['foo.aspx']
    action :config
  end
```

**Comment by EasyAsABC123** [comment]
This should be a pretty elegant change where you just make the handler look in the dictionary for the default documents rather than the current very crude and bruteforce method and I coded previously...

Haven't had time to change this sorry.

**Comment by EasyAsABC123** [comment]
@spuder i just went over this and was about to change a ton of code...however, `:config` isn't meant to be idempotent only `:add` and `:delete` are idempotent.

let me know what the goal is and we I can give you the new recipe block, i can look into making config idempotent...what do you think it should do? should it set the config to only what you pass in?

**Comment by spuder** [comment]
The original goal is to

- remove all built in default_documents 
- add only the 'foo.aspx' to default_documents

Reasoning:

- c:\inetpub\wwwroot\iisstart.htm exists on new windows 2012 vms, and is found by IIS before `foo.aspx`
- theoretically speed up / secure IIS servers by only putting `foo.aspx` in the documents
 
The current work around we have is

```ruby
file 'c:\inetpub\wwwroot\iisstart.htm' do
  action :delete
end

file 'c:\inetpub\wwwroot\iis-85.png' do
  action :delete
end
```

**Comment by EasyAsABC123** [comment]
@spuder 
So basically if `:config` we want to make sure those are the only items in `default_documents` or `mime_types`.  I can do that, I have the code already done...i'll need to write a test and then have someone (hopefully you) test in a real environment since I don't do have access to any chef servers with windows boxes (not part of my full-time job).

Thanks for helping me understand!

I can't promise a timeline since I don't know when i'll have spare time to finish it, hopefully tonight...

**Comment by spuder** [comment]
Thanks. 

We are still on the 4.x.x cookbook, so it will take a little time to get to a point where we can test this.

**Comment by EasyAsABC123** [comment]
This will be a 4.x.x release, so it would just be updating to latest

**Comment by EasyAsABC123** [comment]
@spuder that was a lie...it will be released in 5.x.x...

I can give you the code you would need to change locally to make 4.x.x have the corrected code.

**Comment by spuder** [comment]
5.x.x release is ok. We have a work around in the mean time. 

I could probably test this in test kitchen

**Comment by EasyAsABC123** [comment]
K i'll probably also test it in test kitchen...just need to fix busser on my machine.

**Comment by EasyAsABC123** [comment]
@spuder fixed it in https://github.com/chef-cookbooks/iis/tree/bug-fix_iis-root_default-documents

to test quickly locally you could just update the libraries/processors.rb file to be what is in the above branch

**Comment by fdzedzy** [comment]
@EasyAsABC123 This fix breaks `:add` because `(current_default_documents - default_document).each do |document|` ends up iterating over the existing documents already configured in IIS.  It throws an error like this:  `STDOUT: ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'value' set to 'Default.htm'`

I've written a fix that switches the default and current in :add to solve this problem.  In testing, I also found that `:config` did not work as expected, so I've add a fix for that using your new approach.

PR: [https://github.com/chef-cookbooks/iis/pull/313](https://github.com/chef-cookbooks/iis/pull/313)
